version: "3.8"

services:
  mongodb:
    image: mongo:5.0.3
    container_name: ivy-mongodb
    restart: unless-stopped
    volumes:
      - mongodb-data:/data/db
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: "${DB_USER:-admin}"
      MONGO_INITDB_ROOT_PASSWORD: "${DB_PASSWORD:-Password1!}"

  redis:
    image: redis:6.2.6
    container_name: ivy-redis
    restart: unless-stopped
    volumes:
      - redis-data:/data
    ports:
      - "6379:6379"

  backend:
    image: ivy-backend
    container_name: ivy-backend
    restart: unless-stopped
    build:
      context: ../../
      dockerfile: ./sample/mongoose-app/Dockerfile
    depends_on:
      - mongodb
      - redis
    volumes:
      - storage-data:/usr/app/storage
      - backend-logs:/usr/app/logs
    ports:
      - "4000:${APP_PORT:-80}"
    env_file:
      - .env
    environment:
      DB_HOST: ivy-mongodb
      DB_USER: "${DB_USER:-admin}"
      DB_PASSWORD: "${DB_PASSWORD:-Password1!}"
      QUEUE_HOST: ivy-redis

volumes:
  mongodb-data:
  redis-data:
  storage-data:
  backend-logs:
