version: "3"

services:
  postgresql:
    image: postgres:14.3
    restart: unless-stopped
    container_name: ivy-postgresql
    ports:
      - "5432:5432"
    volumes:
      - postgresql-data:/var/lib/postgresql/data
      - ./initdb:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_DB: "${DB_NAME:-ivy}"
      POSTGRES_USER: "${DB_USER:-ivy}"
      POSTGRES_PASSWORD: "${DB_PASSWORD:-Password1!}"

  redis:
    image: redis:6.2.6
    container_name: ivy-redis
    restart: unless-stopped
    volumes:
      - redis-data:/data
    ports:
      - "6379:6379"

  backend:
    image: ivy-typeorm-backend
    container_name: ivy-typeorm-backend
    restart: unless-stopped
    build:
      context: ../../
      dockerfile: ./sample/typeorm-app/Dockerfile
    depends_on:
      - postgresql
      - redis
    volumes:
      - storage-data:/usr/app/storage
      - backend-logs:/usr/app/logs
    ports:
      - "3000:${APP_PORT:-80}"
    env_file:
      - .env
    environment:
      DB_HOST: ivy-postgresql
      DB_USER: "${DB_USER:-ivy}"
      DB_PASSWORD: "${DB_PASSWORD:-Password1!}"
      QUEUE_HOST: ivy-redis

volumes:
  postgresql-data:
  redis-data:
  storage-data:
  backend-logs:
